// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysMenu = "sys_menu"

// SysMenu mapped from table <sys_menu>
type SysMenu struct {
	ID          int64     `gorm:"column:id;primaryKey" json:"id"`        // id
	Pid         int64     `gorm:"column:pid" json:"pid"`                 // 上级ID，一级菜单为0
	Name        string    `gorm:"column:name" json:"name"`               // 名称
	URL         string    `gorm:"column:url" json:"url"`                 // 菜单URL
	Permissions string    `gorm:"column:permissions" json:"permissions"` // 授权(多个用逗号分隔，如：sys:user:list,sys:user:save)
	Type        int32     `gorm:"column:type" json:"type"`               // 类型   0：菜单   1：按钮
	Icon        string    `gorm:"column:icon" json:"icon"`               // 菜单图标
	Sort        int32     `gorm:"column:sort" json:"sort"`               // 排序
	Creator     int64     `gorm:"column:creator" json:"creator"`         // 创建者
	CreateDate  time.Time `gorm:"column:create_date" json:"createDate"`  // 创建时间
	Updater     int64     `gorm:"column:updater" json:"updater"`         // 更新者
	UpdateDate  time.Time `gorm:"column:update_date" json:"updateDate"`  // 更新时间
}

// TableName SysMenu's table name
func (*SysMenu) TableName() string {
	return TableNameSysMenu
}
