
database: 
  diver: mysql
  host: localhost
  port: 3306
  dbName: go-admin
  username: root
  password: epam_systems

server:
  # context-path: /go-micro-demo
  port: 7081

redis:
  addr: localhost:6379
  password: epam_systems
  db: 0
